import { css } from "./_styled-system/css";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={css({ bg: "bg", color: "text" })} lang="ja">
      <body>{children}</body>
    </html>
  );
}
